### PR TITLE
Add new Function New-PSOneQRCodeText and some more things

### PR DESCRIPTION
**Pull request by T0biii**
- Added a private function New-PSOneQRCode
- Added a public function New-PSOneQRCodeText
- Update README.md (add Command Overview)
- Update Aliases (New-QRCodeText)
- Changed comparison  of $null to the left side  (https://poshadmin.de/?p=1384, https://evotec.xyz/the-curious-case-of-null-should-be-on-the-left-side-of-equality-comparisons-psscriptanalyzer/)

### CODE REVIEW

**Comment by T0biii** [comment]
Ping @TobiasPSP

**Comment by Windos** [comment]
Can confirm this works well. Needed to pull the code from this PR to generate some QR codes from Base64 strings.

Good work @T0biii 👍

**Comment by T0biii** [comment]
@Windos Thanks I hope @TobiasPSP can merge it and publish it in the PowerShell Gallery

**Comment by jfrmilner** [comment]
Thanks for adding this @T0biii, works great and hope to see it on the Gallery soon @TobiasPSP

**Comment by TobiasPSP** [comment]
Sorry for the delay guys!

**Pull request merged**
